spring.application.name=PlayRoleBackendAPI
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/playlore_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=${PORT:8080}
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
server.servlet.context-path=/api
app.upload.dir=uploads/avatars
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB