spring.application.name=PlayRoleBackendAPI
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/playlore_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.address=0.0.0.0
server.port=${PORT:8080}
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
server.servlet.context-path=/api
app.upload.dir=uploads/avatars
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# reCAPTCHA
recaptcha.secret=${RECAPTCHA_SECRET:6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe}
recaptcha.skip-verification=${RECAPTCHA_SKIP_VERIFICATION:false}