package com.playrole.chat.enums;

public enum PermisoCanal {
    LEER_MENSAJES,
    ENVIAR_MENSAJES,
    EDITAR_MENSAJES_PROPIOS,
    ELIMINAR_MENSAJES_PROPIOS,
    ELIMINAR_MENSAJES_AJENOS,
    GESTIONAR_MIEMBROS,
    GESTIONAR_ROLES,
    SILENCIAR,
    ELIMINAR_CANAL
}
